version: '2'

services:
    cache:
        extends:
            file: common.yml
            service: cache
    os-api:
        extends:
            file: common.yml
            service: os-api
        volumes:
            - ../repos/tabulator-py:/repos/tabulator-py
            - ../repos/datapackage-py:/repos/datapackage-py
            - ../repos/babbage.fiscal-data-package:/repos/babbage.fiscal-data-package
            - ../repos/babbage:/repos/babbage
            - ../repos/os-api:/repos/os-api
            - ../repos/jsontableschema-py:/repos/jsontableschema-py
            - ../repos/jsontableschema-sql-py:/repos/jsontableschema-sql-py
        environment:
            - WORKDIR=/repos/os-api
            - OS_API_ENGINE=postgresql://postgres@db/postgres
            - OS_ELASTICSEARCH_ADDRESS=es
    os-packager:
        extends:
            file: common.yml
            service: os-packager
        volumes:
            - ../repos/os-packager:/repos/os-packager
        environment:
            - DEBUG=true
            - PORT=8000
            - WORKDIR=/repos/os-packager
            - OS_EXTERNAL_ADDRESS=dev.openspending.org
            - OS_PACKAGER_CONDUCTOR_HOST=http://dev.openspending.org
    os-viewer:
        extends:
            file: common.yml
            service: os-viewer
        volumes:
            - ../repos/os-viewer:/repos/os-viewer
        environment:
            - DEBUG=true
            - PORT=8000
            - WORKDIR=/repos/os-viewer
            - OS_EXTERNAL_ADDRESS=dev.openspending.org
            - OS_VIEWER_API_HOST=http://dev.openspending.org
            - OS_VIEWER_AUTH_HOST=http://dev.openspending.org
            - OS_VIEWER_SEARCH_HOST=http://dev.openspending.org
    os-conductor:
        extends:
            file: common.yml
            service: os-conductor
        volumes:
            - ../repos/os-conductor:/repos/os-conductor
        environment:
            - WORKDIR=/repos/os-conductor
            - OS_S3_HOSTNAME=fakes3
            - OS_STORAGE_BUCKET_NAME=fake-bucket
            - OS_CONDUCTOR_ENGINE=postgresql://postgres@db/postgres
            - OS_EXTERNAL_ADDRESS=dev.openspending.org
            - OS_ELASTICSEARCH_ADDRESS=es
            - SECRETS_PATH=dev-secrets
    frontend:
        extends:
            file: common.yml
            service: frontend
        volumes:
            - "./frontend/dev-nginx.conf:/etc/nginx/conf.d/dev.conf"
        ports:
            - "8080:8080"
    landing:
      extends:
          file: common.yml
          service: landing
    os-explorer:
      extends:
          file: common.yml
          service: os-explorer
      environment:
            - WORKDIR=/repos/os-explorer
      volumes:
            - ../repos/os-explorer:/repos/os-explorer
    redash:
      extends:
          file: common.yml
          service: redash
      environment:
          REDASH_DATABASE_URL: "postgresql://postgres@db/postgres"
          REDASH_SERVER_NAME: "rd.dev.openspending.org"
          OS_DB_HOST: "db"
          OS_DB_NAME: "postgres"
          OS_DB_PWD: "null"
          OS_DB_USER: "postgres"
    mq:
        extends:
            file: common.yml
            service: mq
    redis:
        extends:
            file: common.yml
            service: redis
    fakes3:
        image: openspending/fakes3
        container_name: "fakes3"
        expose:
          - "80"
    db:
        image: openspending/db
        container_name: "db"
        expose:
          - "5432"
        ports:
          - "15432:5432"
    es:
        image: openspending/es
        container_name: "es"
        expose:
          - "9200"
          - "9300"
        ports:
          - "9200:9200"
