version: '2'

services:
    cache:
        extends:
            file: common.yml
            service: cache
    os-api:
        extends:
            file: common.yml
            service: os-api
        volumes:
            - ../repos/tabulator-py:/repos/tabulator-py
            - ../repos/datapackage-py:/repos/datapackage-py
            - ../repos/babbage.fiscal-data-package:/repos/babbage.fiscal-data-package
            - ../repos/babbage:/repos/babbage
            - ../repos/os-api:/repos/os-api
            - ../repos/jsontableschema-py:/repos/jsontableschema-py
            - ../repos/jsontableschema-sql-py:/repos/jsontableschema-sql-py
        environment:
            - WORKDIR=/repos/os-api
            - OS_API_ENGINE=postgresql://postgres@db/postgres
            - OS_ELASTICSEARCH_ADDRESS=es
    os-packager:
        extends:
            file: common.yml
            service: os-packager
        volumes:
            - ../repos/os-packager:/repos/os-packager
        environment:
            - DEBUG=true
            - PORT=8000
            - WORKDIR=/repos/os-packager
            - OS_EXTERNAL_ADDRESS=dev.openspending.org
            - OS_PACKAGER_CONDUCTOR_HOST=http://dev.openspending.org
    os-viewer:
        extends:
            file: common.yml
            service: os-viewer
        volumes:
            - ../repos/os-viewer:/repos/os-viewer
        environment:
            - DEBUG=true
            - PORT=8000
            - WORKDIR=/repos/os-viewer
            - OS_EXTERNAL_ADDRESS=dev.openspending.org
            - OS_VIEWER_API_HOST=http://dev.openspending.org
            - OS_VIEWER_AUTH_HOST=http://dev.openspending.org
            - OS_VIEWER_SEARCH_HOST=http://dev.openspending.org
            - OS_VIEWER_DATAMINE_HOST=http://rd.dev.openspending.org
    os-conductor:
        extends:
            file: common.yml
            service: os-conductor
        volumes:
            - ../repos/os-conductor:/repos/os-conductor
        environment:
            - WORKDIR=/repos/os-conductor
            - OS_S3_HOSTNAME=fakes3
            - OS_STORAGE_BUCKET_NAME=fake-bucket
            - OS_CONDUCTOR_ENGINE=postgresql://postgres@db/postgres
            - OS_EXTERNAL_ADDRESS=dev.openspending.org
            - OS_ELASTICSEARCH_ADDRESS=es
            - OS_CONDUCTOR_SECRETS_0="eJyN1Umvo0gSAOC/UnpXuh47mJH6wA5mMTsG+YLZzOLE7Etr/vv41XRLM6OeUuU1U6FQRGR8f3yUXVe2+eeYp0M+fTb5/vGPbx/kfInR5btTFSV9xMHVsvF41Rvi47dvH6+hWpIp/3zlz6+n378OJ8qq+c1x2W+WowasJ37TxOjHzQ0Yqiq+WJVjWY1nbZE93CGA3c0xtblIqQKRbXWODNYtOf5SnUOyWHggT4GhDuHC2R1/AxL7YuzVUYa7PdjnyiqpqO+Bt8iPcBx1UjeMxTnV1+vlJfnaESVuGSX2hOqmwa9Tb3A3gEiyK9TccH+KTyC4HVUiZrI9Ksg9X3HOSNMcDb1Sc/b7gpu4BJVnJjutVrNvzPbIcOUGCAxBWqUhPPKqkZC+s5YLLFoy/cjLzo6zaVJYxtKsqpC4Uc/J13xGj8eS2XKWpxAcv4Hs6UY5uYdFNkj542kvFucHCqHok44WV8/cr/MRr9MFXSjUTtEZrunSGAflGkJEOtbuDeCtsFa"
            - OS_CONDUCTOR_SECRETS_1="VpZZUjz48lrbPGYca0FAnmCFD3aojPtOtqsDaLMd274orJUvvE6hi2zWAEN7AeIxOqTbGQIR8n6y2h/NSKFdNzXvZpdKHRMO1i7kJMom/Cj/VTIfJd9caV1LZvFi1bmAQRCZ7UvwcnQXfflcD8XO6n4piTGj/KW2BFXC+BaShE8pKUuoXgirSPj4l/Epn0Rl+d3MfCUlYNWzwt+6agkdzoVNySsSBtR6v5wLZIA24pptt/M7Rp2ShUiWziw6irXSJnHcOG1UJFlsbrwNdJVRqMubpKklWz33L49J8v6+iRgJvdlsCWL6u0VrCL4xZb/vh+RX27oUQNozNL9ArVzUYfdBkeueYPFjiZFdaqQ3MSaCNYSOHPKtClnP7xdSdBU5iBO5ISDJuAE23KrJEvoxElmHFgUJ4qw2ZhbskKa8+QaiEogL74loRielx2ysWQ2c2EQU8OYhwpneEO0Tr3ZXq2oAz0f0UqevRCBc+uLdS4kGewpmVSLPcyp3oFKmjDPN1ez"
            - OS_CONDUCTOR_SECRETS_2="z6Ib/XV6s7buDU00ZfPgSIqIRisTD7WS2vJCtyWT4iSSWYOx2SKawuxIp0YTlP1R16COOPnFFEaG7gYawlhfZUFLC5p/YgoI+5Lg5PrQqGbXKLLUy9a/UMINxG6i7VWVvu+Nu+E0/1uQ7FDbyoPZYvV5ju0p0ebPwKS1Qxb+ssJzRhmbG1tvos0L5vDTB8sWa7enSCtugQiV1DlvRvwEaY8apBWrvMCiGcSX9UeKYpWW+fZdO/5NeIU5R78yNr+hT3pw2LLwfVz7bftXH69bPEIz+aXTlHhGZbTk4Ffj6yHDlUOy4RBvZeEXlt2C8MDicnGvmhbXHwgCwUYbJhd4QbkF93s7aRITzEYI/pmdAPp7IJXD7uUsFPUD4x6eGHqag67EybOV23nhu7DYJH74E1x3clT7XMNl5lUTwWod2cmfS+Tl+15thQTfAY6t7/pU7PApFk4Rbiq+vTaOeqJuu6AQxuALRdNTuCJAU5BqI16u+PrjE9Xw2ux7y2zwHRVTzhw"
            - OS_CONDUCTOR_SECRETS_3="LkLRJN7j31p1DZ8VMa0cCyHv/dD72JEuuUYFUl7c3aySXUgxRM1EaPRhz6aIxtkHcV6rpDvcHdpeDWS4+PZpbaZNOMpfleyeRm8rXGlzRcxTQ5oCyvH63GnT1FZMNPlQCNf6ld4i5i6mIuQ4GHSLQOsxyaYjbv3ROnVtlvWyT3OqYIhlZalTOPSa17ZLNJmHuZGCxV4tNqXNl7BfZRdnklZ1pycqLPKwe9dbceXMwcS1wjOUgHHFxRGq1YO5CKOcc+4sKh3blMvrsaGpCbHuzfVojP277/fwA9wRFP4W4i+6PrTuj+RoxmUoimURFAG+04QaMPMyUCCNMEwgnwsJwyl0DHphiFFGOQzeb3Gz38HmMd8SDsw5WD6TLvnDxTne1ulf2Oi5XO6yv83h5xasyZXNv2jqWRmRbg3ixLLXt48ntive778/1TewM+w/BUq34vjJ1j+CpU38DMsf4XKG/gZlr9C5TvCT7D8FSpv4C8s/2N0/qdfH//8Fx15/nA="
    frontend:
        extends:
            file: common.yml
            service: frontend
        volumes:
            - "./frontend/dev-nginx.conf:/etc/nginx/conf.d/dev.conf"
        ports:
            - "8080:8080"
    landing:
      extends:
          file: common.yml
          service: landing
    os-explorer:
      extends:
          file: common.yml
          service: os-explorer
      environment:
            - WORKDIR=/repos/os-explorer
      volumes:
            - ../repos/os-explorer:/repos/os-explorer
    os-admin:
      extends:
          file: common.yml
          service: os-admin
      environment:
            - WORKDIR=/repos/os-admin
      volumes:
            - ../repos/os-admin:/repos/os-admin
    os-fdp-adapters:
      extends:
          file: common.yml
          service: os-fdp-adapters
      environment:
            - WORKDIR=/repos/os-fdp-adapters
            - OS_FDP_ADAPTER_ENDPOINT=http://dev.openspending.org/fdp-adapter/convert
      volumes:
            - ../repos/os-fdp-adapters:/repos/os-fdp-adapters
    redash:
      extends:
          file: common.yml
          service: redash
      environment:
          REDASH_DATABASE_URL: "postgresql://postgres@db/postgres"
          REDASH_SERVER_NAME: "rd.dev.openspending.org"
          OS_DB_HOST: "db"
          OS_DB_NAME: "postgres"
          OS_DB_PWD: "null"
          OS_DB_USER: "postgres"
    mq:
        extends:
            file: common.yml
            service: mq
    celery-flower:
        extends:
            file: common.yml
            service: celery-flower
    redis:
        extends:
            file: common.yml
            service: redis
    fakes3:
        image: openspending/fakes3
        container_name: "fakes3"
        expose:
          - "80"
    db:
        image: openspending/db
        container_name: "db"
        expose:
          - "5432"
        ports:
          - "15432:5432"
    es:
        image: openspending/es
        container_name: "es"
        expose:
          - "9200"
          - "9300"
        ports:
          - "9200:9200"
