version: '2'

services:
    cache:
        extends:
            file: common.yml
            service: cache
        logging:
            driver: awslogs
            options:
                awslogs-group: openspending
                awslogs-stream: cache
    os-api:
        extends:
            file: common.yml
            service: os-api
        environment:
            - WORKDIR=app
        logging:
            driver: awslogs
            options:
                awslogs-group: openspending
                awslogs-stream: os-api
    os-packager:
        extends:
            file: common.yml
            service: os-packager
        environment:
            - WORKDIR=app
            - OS_EXTERNAL_ADDRESS=s145.okserver.org
        logging:
            driver: awslogs
            options:
                awslogs-group: openspending
                awslogs-stream: os-packager
    os-viewer:
        extends:
            file: common.yml
            service: os-viewer
        environment:
            - WORKDIR=app
            - PORT=8000
            - OS_EXTERNAL_ADDRESS=s145.okserver.org
            - OS_VIEWER_API_HOST=s145.okserver.org
        logging:
            driver: awslogs
            options:
                awslogs-group: openspending
                awslogs-stream: os-viewer
    os-conductor:
        extends:
            file: common.yml
            service: os-conductor
        environment:
            - WORKDIR=app
            - OS_EXTERNAL_ADDRESS=s145.okserver.org
            - SECRETS_PATH=prod-secrets
        logging:
            driver: awslogs
            options:
                awslogs-group: openspending
                awslogs-stream: os-conductor
    frontend:
        extends:
            file: common.yml
            service: frontend
        logging:
            driver: awslogs
            options:
                awslogs-group: openspending
                awslogs-stream: frontend
    mq:
        extends:
            file: common.yml
            service: mq
        logging:
            driver: awslogs
            options:
                awslogs-group: openspending
                awslogs-stream: mq
